[[redirects]]
  from = "/app/*"          # SPA routes
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/static/*"       # allow static assets
  to = "/static/:splat"
  status = 200
